### ISSUE TITLE
A dashboard!

### ISSUE THREAD

**Issue by lmeerkatz** [Sundae-Shop-Consulting/Volunteers#49]
Take all the beautiful initial reports and make a dashboard from them. See [V4S Dashboard](https://github.com/Sundae-Shop-Consulting/Volunteers/wiki/MVP-Features#v4s-volunteers-dashboard) for inspiration, but also feel free to make up whatever draft version makes sense to you.

**Comment by mcculloughcm** [comment]
Quick brainstorm of questions we can answer via dashboard:
- How many active volunteers do we have?
- Who are our best volunteers? How many hours have they volunteered?
	- Lifetime
	- This Year
	- Last 3 Months
- How many volunteer applicants do we have, and what positions have they applied for?
- What are our most popular volunteer activities?
- What are our LEAST popular volunteer activities?
- What volunteers have become inactive (ie, their last log was 3 months ago or similar)
- How do volunteer hours this year compare to last year?
- How many open volunteering opportunities do we have?
- How many volunteers do we NEED and for what activities?
- Do we have upcoming shifts without volunteers?
